# Application
spring.application.name=CampusZen API
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/campuszen
spring.datasource.username=campuszen_user
spring.datasource.password=votre_mot_de_passe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect